kind: ServiceAccount
apiVersion: v1
metadata:
  name: emoji
  namespace: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: emoji
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-svc
      version: v11
  template:
    metadata:
      labels:
        app: emoji-svc
        version: v11
    spec:
      shareProcessNamespace: true
      serviceAccountName: emoji
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
        name: emoji-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
      - name: emojivoto-emoji-instrumentation
        image: keyval/otel-go-agent:v0.5.4
        env:
        - name: OTEL_TARGET_EXE
          value: /usr/local/bin/emojivoto-emoji-svc
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "jaeger-collector.observability.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "emojivoto-emoji"
        securityContext:
          runAsUser: 0
          capabilities:
            add:
              - SYS_PTRACE
          privileged: true
        volumeMounts:
          - mountPath: /sys/kernel/debug
            name: kernel-debug
      volumes:
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-svc
  namespace: emojivoto
spec:
  selector:
    app: emoji-svc
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
