apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: emoji-svc-np
  namespace: emojivoto
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30082
  selector:
    app: emoji-svc
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: voting-svc-np
  namespace: emojivoto
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30083
  selector:
    app: voting-svc
  type: NodePort
